# !/usr/bin/env python
# coding: utf-8
# created by leiyangs on 2018/2/9.
import uuid
import time
import datetime
GMT_FORMAT = '%a, %d %b %Y %H:%M:%S GMT'


class MdnMsg(object):
    now_date = datetime.datetime.utcnow()
    HeadDate = now_date.strftime(GMT_FORMAT)
    HeadDate_co = now_date.strftime("%Y/%m/%d %H:%M")
    Msg_Id = str(uuid.uuid5(uuid.NAMESPACE_DNS, str(time.time())))
    As3To = "53000001"
    As3From = "DXPENT0000016069"  # 正式通道
    Boundary = str(uuid.uuid5(uuid.NAMESPACE_DNS, str(time.time()) + "__"))
    OriMsgId = ""

    def __init__(self, msgId,file_path):
        self.OriMsgId = msgId
        self.file_path=file_path

    def __call__(self):
        result = """Subject: Message Disposition Notification
Date:{HeadDate}
Message-Id: {Message_Id}
MIME-Version: 1.0
AS3-To: {As3To}
AS3-From: {As3From}
MIME-Version: 1.0
AS3-Version: 1.1
Content-Type: multipart/report;Report-Type=disposition-notification;boundary="{Boundary}"

--{Boundary}

Message from {As3To} to {As3From} has been received on {HeadDate_co}

Generated by Automatic Reply System.

--{Boundary}
Content-Type: message/disposition-notification

Reporting-UA: {As3From};Eport Client1.1
Original-Recipient: rfc822; {As3From}
Final-Recipient: rfc822; {As3From}
Original-Message-ID: {OriMsgId}
Disposition: Automatic-action/mdn-sent-automatically;processed
0101001101001000@TCS"""
        d={
            "HeadDate":self.HeadDate,
            "Message_Id":self.Msg_Id,
            "As3To":self.As3To,
            "As3From":self.As3From,
            "Boundary":self.Boundary,
            "HeadDate_co":self.HeadDate_co,
            "OriMsgId":self.OriMsgId,
        }
        result=result.format(**d)
        with open(self.file_path,"w",encoding='utf-8') as f:
            f.write(result)
            f.flush()


if __name__ == '__main__':
    MdnMsg("1518142194378.2088903@iFwKnYVrbz7DbcMI4hPN4I4=","a.txt")()
    time.sleep(20)
